name: sales-assistant
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - requests=2.31.0
  - python-dotenv=1.0.0
  - tenacity=8.2.3
  - apscheduler=3.10.4
  - pytest=7.4.3
  - pytest-asyncio=0.21.1
  - pytest-cov=4.1.0
  - beautifulsoup4=4.12.2  # <-- ensure this line is present
  - pip
  - pip:
    - "openai<1.0.0"
    - async_timeout==4.0.2
    - python-dateutil>=2.8.2
    - google-api-python-client
    - google-auth-httplib2
    - google-auth-oauthlib
    - feedparser
    - schedule
    - groq
    - psycopg2-binary
    - pyodbc
